 # LAS Point Cloud Data Analysis

 Source: https://medium.com/spatial-data-science/an-easy-way-to-work-and-visualize-lidar-data-in-python-eed0e028996c

In [1]:
# Import Library
import laspy
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
# Read LAS file
las_data = laspy.read("../data/NEONDSSampleLiDARPointCloud.las")
las_data

<LasData(1.3, point fmt: <PointFormat(1, 0 bytes of extra dims)>, 6609829 points, 2 vlrs)>

In [5]:
las_data.header

<LasHeader(1.3, <PointFormat(1, 0 bytes of extra dims)>)>

In [8]:
las_data.points

<ScaleAwarePointRecord(fmt: <PointFormat(1, 0 bytes of extra dims)>, len: 6609829, point size: 28)>

In [9]:
list(las_data.point_format.dimension_names)

['X',
 'Y',
 'Z',
 'intensity',
 'return_number',
 'number_of_returns',
 'scan_direction_flag',
 'edge_of_flight_line',
 'classification',
 'synthetic',
 'key_point',
 'withheld',
 'scan_angle_rank',
 'user_data',
 'point_source_id',
 'gps_time']

In [12]:
las_data.X

array([156562, 156494, 156427, ...,  74934,  74851,  74783])

In [13]:
las_data.intensity

array([15, 18, 18, ...,  7,  7,  6], dtype=uint16)

In [14]:
las_data.gps_time

array([63501.94922959, 63501.94923959, 63501.94924959, ...,
       62336.555153  , 62336.555163  , 62336.555173  ])

In [16]:
# Show Classifications
set(las_data.classification)

{1, 2, 5, 6}

1 = Unassigned

2 = Ground

5 = High Vegetation

6 = Building

 ## Creating, Filtering, and Writing Point Cloud Data
 

In [18]:
point_data = np.vstack(
    (las_data.x, las_data.y, las_data.z)
    ).transpose()

In [19]:
point_data

array([[2.56999540e+05, 4.11199951e+06, 4.62310000e+02],
       [2.56998860e+05, 4.11199952e+06, 4.62260000e+02],
       [2.56998190e+05, 4.11199952e+06, 4.62430000e+02],
       ...,
       [2.56183260e+05, 4.11199987e+06, 4.81260000e+02],
       [2.56182430e+05, 4.11199985e+06, 4.81770000e+02],
       [2.56181750e+05, 4.11199986e+06, 4.81790000e+02]])

In [20]:
buildings = laspy.create(
    point_format=las_data.header.point_format, 
    file_version=las_data.header.version
)
buildings.points = las_data.points[las_data.classification == 6]

In [21]:
buildings.write("../data/buildings.las")

## 3D Point Cloud Visualization

In [22]:
geom = o3d.geometry.PointCloud()
geom.points = o3d.utility.Vector3dVector(point_data)
o3d.visualization.draw_geometries([geom])